spring.application.name=payments
server.port=${PORT:8081}
khqr.profile-id=${KHQR_PROFILE_ID}
khqr.api-key=${KHQR_API_KEY}
khqr.base-url=https://khqr.cc/api
khqr.callback-url=${KHQR_CALLBACK_URL:https://hourshop-backend.onrender.com/api/payment/webhook}