spring.application.name=payments
server.port=8081
khqr.profile-id=DHwNnYvEEE0ER5l8ENmlujN2XtbOxzi8
khqr.api-key=${KHQR_API_KEY:mmirjkViBokQ403RrxNloOZsqfcjOGrH}
khqr.base-url=https://khqr.cc/api
khqr.callback-url=https://unengaged-starfish-cusp.ngrok-free.dev/api/payment/webhook